services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: local-clickhouse
    environment:
      CLICKHOUSE_USER: 'default'
      CLICKHOUSE_PASSWORD: 'default'
    ports:
      # HTTP interface
      - "8123:8123"
      # Native client interface
      - "9000:9000"
    volumes:
      - ./clickhouse_schema.sql:/docker-entrypoint-initdb.d/initdb.sql:z
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
  clickhouse_logs:

